server.port=9090

spring.application.name=API-GATEWAY

# =========================
# USER SERVICE
# =========================
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/user/**

spring.cloud.gateway.server.webflux.routes[1].id=user-auth-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/auth/**

# =========================
# PRODUCT SERVICE
# =========================
spring.cloud.gateway.server.webflux.routes[2].id=product-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/products/**

# =========================
# CART SERVICE
# =========================
spring.cloud.gateway.server.webflux.routes[3].id=cart-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://cart-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/cart/**

# =========================
# ORDER SERVICE
# =========================
spring.cloud.gateway.server.webflux.routes[4].id=order-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/orders/**

# =========================
# DELIVERY SERVICE
# =========================
spring.cloud.gateway.server.webflux.routes[5].id=delivery-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://DELIVERY-SERVICE
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/delivery/**

# =========================
# NOTIFICATION SERVICE
# =========================
spring.cloud.gateway.server.webflux.routes[6].id=notification-service
spring.cloud.gateway.server.webflux.routes[6].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/notifications/**

# =========================
# TICKET SERVICE
# =========================
spring.cloud.gateway.server.webflux.routes[7].id=ticket-service
spring.cloud.gateway.server.webflux.routes[7].uri=lb://TICKET-SERVICE
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/tickets/**

# =========================
# UPLOAD / PAYMENT SCREENSHOT
# =========================
spring.cloud.gateway.server.webflux.routes[8].id=order-upload-service
spring.cloud.gateway.server.webflux.routes[8].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/api/upload/**

spring.cloud.gateway.server.webflux.routes[9].id=order-return-service
spring.cloud.gateway.server.webflux.routes[9].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/api/returns/**

# =========================
# ADMIN SERVICE
# =========================
spring.cloud.gateway.server.webflux.routes[10].id=admin-service
spring.cloud.gateway.server.webflux.routes[10].uri=lb://ADMIN-SERVICE
spring.cloud.gateway.server.webflux.routes[10].predicates[0]=Path=/api/admin/**

# =========================
# EUREKA
# =========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# =========================
# CORS
# =========================
spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS,PATCH
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowCredentials=true
